### ISSUE TITLE
Replace Github Link and Star

### ISSUE THREAD

**Issue by tpage99** [tpage99/a11yfirst#2]
Github link/star still references the Gatsby Starter from Hasura. Update to correct github repository: https://github.com/tpage99/a11yfirst/

**Comment by sa160690** [comment]
Hi @tpage99, can I take up this issue? Can you point me to the documentation where I have to make the changes?

**Comment by tpage99** [comment]
@sa160690 take a look at the config.js file in the root.

**Comment by sa160690** [comment]
Hi @tpage99, I have raised a pull request.
