### ISSUE TITLE
Start linking resources from Marcy's blog post

### ISSUE THREAD

**Issue by tpage99** [tpage99/a11yfirst#4]
Blog post referenced in introduction/Web Developer Resources material only has headers. Link and short summaries regarding the resources would be helpful for developers looking for specific information.

**Comment by RafaelMassoniSS** [comment]
Hi @tpage99, I'd like to do this issue! Would you assign me, please?

**Comment by RafaelMassoniSS** [comment]
Hi @tpage99, I'm very sorry but I won't be able to continue pursuing this issue, I have unassigned myself so somebody else may come along. Again, I sincerely apologize.
