### ISSUE TITLE
Update "Edit on Github" button

### ISSUE THREAD

**Issue by tpage99** [tpage99/a11yfirst#7]
The "Edit on Github" button still references Gatsby starter project that was used. Update to current repo.

**Comment by justinjunodev** [comment]
@tpage99 mind if I tackle this one?

**Comment by guntbert** [comment]
@tpage99 nice idea, creating good first issues™
May I suggest to give some guidance as to the relevant files?

**Comment by justinjunodev** [comment]
Go for it @guntbert 👍

**Comment by guntbert** [comment]
@justinjunodev     :question:  
I have no idea (yet) about this project's structure :smiling_imp:

**Comment by justinjunodev** [comment]
No worries. PR created and submitted here: https://github.com/tpage99/a11yfirst/pull/9

**Comment by tpage99** [comment]
@guntbert I understand the notion regarding giving some guidance/ideas to relevant files to alter but I do feel people should try to spend some time looking over the available documentation. Even if you have basic familiarity with Gatsby it shouldn't prove too difficult but perhaps I should provide more guidance there where to look if people feel stuck. 

I will try to keep responding when people ask about file location for a specific issue. I myself am not familiar with this Gatsby starter, so I've had to spend a little time getting familiar with it as well before responding. 

@justinjunodev thanks! I'll take a look - I may not be able to get to it for a bit but will hopefully have it addressed soon.
